apiVersion: v1
kind: ConfigMap
metadata:
  name: accounts-config
  namespace: sparkfund
data:
  APP_ENV: development
  LOG_LEVEL: debug
  SERVER_PORT: "8080"
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: sparkfund
  DB_SSL_MODE: disable