apiVersion: v1
kind: ConfigMap
metadata:
  name: moneypulse-config
data:
  environment: production
  log_level: info
  http_port: "8080"
  metrics_port: "9090"
  tracing_enabled: "true"
  cors_allowed_origins: "*" 