apiVersion: apps/v1
kind: Deployment
metadata:
  name: aml-service
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: aml-service
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
          env:
            - name: ENVIRONMENT
              value: production
            - name: PORT
              value: "8080"
            - name: DB_SSLMODE
              value: "require" 