apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sparkfund

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml
  - ingress-patch.yaml

configMapGenerator:
  - name: aml-service-config
    behavior: merge
    literals:
      - ENVIRONMENT=production
      - PORT=8080
      - DB_SSLMODE=require

secretGenerator:
  - name: aml-service-secrets
    behavior: merge
    envs:
      - secrets.env 