apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: credit-scoring-service-pdb
  namespace: sparkfund
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: credit-scoring-service 