apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: credit-scoring-service-monitor
  namespace: sparkfund
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: credit-scoring-service
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
    scheme: http
    tlsConfig:
      insecureSkipVerify: true
  - port: health
    interval: 30s
    path: /health
    scheme: http
    tlsConfig:
      insecureSkipVerify: true 