replicaCount: 2

image:
  repository: sparkfund/kyc-service
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9090"
  prometheus.io/path: "/metrics"

podSecurityContext:
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: kyc.sparkfund.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: kyc-tls
      hosts:
        - kyc.sparkfund.com

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - kyc-service
        topologyKey: kubernetes.io/hostname

env:
  - name: ENVIRONMENT
    value: production
  - name: PORT
    value: "8080"
  - name: LOG_LEVEL
    value: info
  - name: DB_HOST
    valueFrom:
      secretKeyRef:
        name: kyc-db-credentials
        key: host
  - name: DB_PORT
    valueFrom:
      secretKeyRef:
        name: kyc-db-credentials
        key: port
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: kyc-db-credentials
        key: username
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: kyc-db-credentials
        key: password
  - name: DB_NAME
    value: kyc_service
  - name: DB_SSLMODE
    value: verify-full
  - name: REDIS_HOST
    valueFrom:
      secretKeyRef:
        name: kyc-redis-credentials
        key: host
  - name: REDIS_PORT
    valueFrom:
      secretKeyRef:
        name: kyc-redis-credentials
        key: port
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: kyc-redis-credentials
        key: password
  - name: JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: kyc-jwt
        key: secret
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: kyc-aws-credentials
        key: access-key-id
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: kyc-aws-credentials
        key: secret-access-key
  - name: AWS_S3_BUCKET
    value: kyc-documents-prod
  - name: ONFIDO_API_KEY
    valueFrom:
      secretKeyRef:
        name: kyc-onfido-credentials
        key: api-key
  - name: ONFIDO_WEBHOOK_SECRET
    valueFrom:
      secretKeyRef:
        name: kyc-onfido-credentials
        key: webhook-secret

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  httpGet:
    path: /ready
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

serviceMonitor:
  enabled: true
  interval: 15s
  scrapeTimeout: 14s
  namespace: monitoring

postgresql:
  enabled: true
  auth:
    username: kyc_user
    database: kyc_service
    existingSecret: kyc-db-credentials
  primary:
    persistence:
      size: 10Gi
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: 1000m

redis:
  enabled: true
  auth:
    existingSecret: kyc-redis-credentials
  master:
    persistence:
      size: 5Gi
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m 