version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: money-pulse-postgres
    environment:
      POSTGRES_USER: moneypulse
      POSTGRES_PASSWORD: moneypulse
      POSTGRES_DB: moneypulse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - money-pulse-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U moneypulse"]
      interval: 5s
      timeout: 5s
      retries: 5

  users-service:
    build:
      context: .
      dockerfile: internal/users/Dockerfile
    container_name: money-pulse-users
    environment:
      - DATABASE_URL=postgres://moneypulse:moneypulse@postgres:5432/moneypulse?sslmode=disable
      - PORT=8080
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - money-pulse-network

  accounts-service:
    build:
      context: .
      dockerfile: internal/accounts/Dockerfile
    container_name: money-pulse-accounts
    environment:
      - DATABASE_URL=postgres://moneypulse:moneypulse@postgres:5432/moneypulse?sslmode=disable
      - PORT=8080
    ports:
      - "8082:8080"
    depends_on:
      postgres:
        condition: service_healthy
      users-service:
        condition: service_started
    networks:
      - money-pulse-network

  transactions-service:
    build:
      context: .
      dockerfile: internal/transactions/Dockerfile
    container_name: money-pulse-transactions
    environment:
      - DATABASE_URL=postgres://moneypulse:moneypulse@postgres:5432/moneypulse?sslmode=disable
      - PORT=8080
    ports:
      - "8083:8080"
    depends_on:
      postgres:
        condition: service_healthy
      users-service:
        condition: service_started
      accounts-service:
        condition: service_started
    networks:
      - money-pulse-network

  investments-service:
    build:
      context: .
      dockerfile: internal/investments/Dockerfile
    container_name: money-pulse-investments
    environment:
      - DATABASE_URL=postgres://moneypulse:moneypulse@postgres:5432/moneypulse?sslmode=disable
      - PORT=8080
    ports:
      - "8084:8080"
    depends_on:
      postgres:
        condition: service_healthy
      users-service:
        condition: service_started
      accounts-service:
        condition: service_started
    networks:
      - money-pulse-network

  loans-service:
    build:
      context: .
      dockerfile: internal/loans/Dockerfile
    container_name: money-pulse-loans
    environment:
      - DATABASE_URL=postgres://moneypulse:moneypulse@postgres:5432/moneypulse?sslmode=disable
      - PORT=8080
    ports:
      - "8085:8080"
    depends_on:
      postgres:
        condition: service_healthy
      users-service:
        condition: service_started
      accounts-service:
        condition: service_started
    networks:
      - money-pulse-network

  reports-service:
    build:
      context: .
      dockerfile: internal/reports/Dockerfile
    container_name: money-pulse-reports
    environment:
      - DATABASE_URL=postgres://moneypulse:moneypulse@postgres:5432/moneypulse?sslmode=disable
      - PORT=8080
    ports:
      - "8086:8080"
    depends_on:
      postgres:
        condition: service_healthy
      users-service:
        condition: service_started
      accounts-service:
        condition: service_started
      transactions-service:
        condition: service_started
      investments-service:
        condition: service_started
      loans-service:
        condition: service_started
    networks:
      - money-pulse-network

volumes:
  postgres_data:

networks:
  money-pulse-network:
    driver: bridge
