services:
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - INVESTMENT_SERVICE_URL=http://investment-service
      - INVESTMENT_SERVICE_PORT=8080
      - REDIS_URL=redis:6379
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
    volumes:
      - ./services/api-gateway:/app
    networks:
      - sparkfund-network

  investment-service:
    build:
      context: ./services/investment-service
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=sparkfund
      - DB_PASSWORD=sparkfund123
      - DB_NAME=sparkfund
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
    volumes:
      - ./services/investment-service:/app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sparkfund-network

  postgres:
    image: postgres:14-alpine
    container_name: sparkfund-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sparkfund
      - POSTGRES_PASSWORD=sparkfund123
      - POSTGRES_DB=sparkfund
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sparkfund"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - sparkfund-network

  redis:
    image: redis:7-alpine
    container_name: sparkfund-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sparkfund-network

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: sparkfund-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    networks:
      - sparkfund-network

  grafana:
    image: grafana/grafana:10.0.0
    container_name: sparkfund-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - sparkfund-network

volumes:
  postgres_data:
  redis_data:
  grafana_data:

networks:
  sparkfund-network:
    name: sparkfund-network
    driver: bridge
