version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: money-pulse-postgres
    environment:
      POSTGRES_USER: moneypulse
      POSTGRES_PASSWORD: moneypulse
      POSTGRES_DB: moneypulse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - money-pulse-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U moneypulse"]
      interval: 5s
      timeout: 5s
      retries: 5

  users-service:
    build:
      context: .
      dockerfile: internal/users/Dockerfile
    container_name: money-pulse-users
    environment:
      - DATABASE_URL=postgres://moneypulse:moneypulse@postgres:5432/moneypulse?sslmode=disable
      - PORT=8080
      - OTEL_SERVICE_NAME=users-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
      otel-collector:
        condition: service_started
    networks:
      - money-pulse-network

  accounts-service:
    build:
      context: .
      dockerfile: internal/accounts/Dockerfile
    container_name: money-pulse-accounts
    environment:
      - DATABASE_URL=postgres://moneypulse:moneypulse@postgres:5432/moneypulse?sslmode=disable
      - PORT=8080
      - OTEL_SERVICE_NAME=accounts-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
    ports:
      - "8082:8080"
    depends_on:
      postgres:
        condition: service_healthy
      users-service:
        condition: service_started
      otel-collector:
        condition: service_started
    networks:
      - money-pulse-network

  transactions-service:
    build:
      context: .
      dockerfile: internal/transactions/Dockerfile
    container_name: money-pulse-transactions
    environment:
      - DATABASE_URL=postgres://moneypulse:moneypulse@postgres:5432/moneypulse?sslmode=disable
      - PORT=8080
      - OTEL_SERVICE_NAME=transactions-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
    ports:
      - "8083:8080"
    depends_on:
      postgres:
        condition: service_healthy
      users-service:
        condition: service_started
      accounts-service:
        condition: service_started
      otel-collector:
        condition: service_started
    networks:
      - money-pulse-network

  investments-service:
    build:
      context: .
      dockerfile: internal/investments/Dockerfile
    container_name: money-pulse-investments
    environment:
      - DATABASE_URL=postgres://moneypulse:moneypulse@postgres:5432/moneypulse?sslmode=disable
      - PORT=8080
      - OTEL_SERVICE_NAME=investments-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
    ports:
      - "8084:8080"
    depends_on:
      postgres:
        condition: service_healthy
      users-service:
        condition: service_started
      accounts-service:
        condition: service_started
      otel-collector:
        condition: service_started
    networks:
      - money-pulse-network

  loans-service:
    build:
      context: .
      dockerfile: internal/loans/Dockerfile
    container_name: money-pulse-loans
    environment:
      - DATABASE_URL=postgres://moneypulse:moneypulse@postgres:5432/moneypulse?sslmode=disable
      - PORT=8080
      - OTEL_SERVICE_NAME=loans-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
    ports:
      - "8085:8080"
    depends_on:
      postgres:
        condition: service_healthy
      users-service:
        condition: service_started
      accounts-service:
        condition: service_started
      otel-collector:
        condition: service_started
    networks:
      - money-pulse-network

  reports-service:
    build:
      context: .
      dockerfile: internal/reports/Dockerfile
    container_name: money-pulse-reports
    environment:
      - DATABASE_URL=postgres://moneypulse:moneypulse@postgres:5432/moneypulse?sslmode=disable
      - PORT=8080
      - OTEL_SERVICE_NAME=reports-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
    ports:
      - "8086:8080"
    depends_on:
      postgres:
        condition: service_healthy
      users-service:
        condition: service_started
      accounts-service:
        condition: service_started
      transactions-service:
        condition: service_started
      investments-service:
        condition: service_started
      loans-service:
        condition: service_started
      otel-collector:
        condition: service_started
    networks:
      - money-pulse-network

  auth-service:
    build:
      context: ./auth-service
    container_name: money-pulse-auth-service
    restart: always
    ports:
      - "8085:8085"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=auth_db
      - ACCESS_TOKEN_SECRET=your_secret_key_here
      - REFRESH_TOKEN_SECRET=your_refresh_secret_key
      - SERVICE_HOST=auth-service
      - CONSUL_ADDR=consul:8500
      - OTEL_SERVICE_NAME=auth-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
    depends_on:
      - postgres
      - consul
      - otel-collector
    networks:
      - money-pulse-network

  consul:
    image: consul:latest
    container_name: money-pulse-consul
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    networks:
      - money-pulse-network

  prometheus:
    image: prom/prometheus:latest
    container_name: money-pulse-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    networks:
      - money-pulse-network

  grafana:
    image: grafana/grafana:latest
    container_name: money-pulse-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
      - loki
    networks:
      - money-pulse-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: money-pulse-jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "14268:14268" # Collector HTTP
      - "6831:6831/udp" # Agent
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      - money-pulse-network

  loki:
    image: grafana/loki:latest
    container_name: money-pulse-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - money-pulse-network

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: money-pulse-otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./observability/otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "8888:8888" # Prometheus metrics
      - "8889:8889" # Prometheus exporter
    depends_on:
      - jaeger
      - prometheus
      - loki
    networks:
      - money-pulse-network

volumes:
  postgres_data:

networks:
  money-pulse-network:
    driver: bridge
