version: "3.8"

services:
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "8080:8080"
    environment:
      - ENV=development
    depends_on:
      - auth-service
      - kyc-service
      - investment-service
      - aml-service

  auth-service:
    build: ./services/auth-service
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis

  kyc-service:
    build: ./services/kyc-service
    volumes:
      - kyc-data:/data/documents
    environment:
      - STORAGE_PATH=/data/documents
    depends_on:
      - postgres

  investment-service:
    build: ./services/investment-service
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres

  aml-service:
    build: ./services/aml-service
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres

  security-monitoring:
    build: ./services/security-monitoring-service
    depends_on:
      - elasticsearch

  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=sparkfund
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    volumes:
      - redis-data:/data

  elasticsearch:
    image: elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
    volumes:
      - elastic-data:/usr/share/elasticsearch/data

volumes:
  postgres-data:
  redis-data:
  kyc-data:
    driver: bridge
