AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Money Pulse Lambda Application

Resources:
  MoneyPulseFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 10
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: any

Outputs:
  MoneyPulseFunction:
    Description: "Money Pulse Lambda Function ARN"
    Value: !GetAtt MoneyPulseFunction.Arn
  MoneyPulseApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
