# Default values for accounts-service
replicaCount: 1

image:
  repository: ghcr.io/adil-faiyaz98/money-pulse/accounts-service
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  httpPort: 80
  grpcPort: 50051

config:
  logLevel: info
  environment: development
  httpPort: 8080
  grpcPort: 50051

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}