adminUser: admin
adminPassword: admin

persistence:
  enabled: true
  size: 10Gi

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server:9090
        access: proxy
        isDefault: true
        editable: false
        version: 1
        jsonData:
          timeInterval: "15s"
          queryTimeout: "30s"
          httpMethod: "GET"
          exemplarTraceIdDestinations:
            - name: trace_id
              datasourceUid: jaeger

dashboards:
  default:
    aml-service:
      gnetId: 12345
      revision: 1
      datasource: Prometheus
    kyc-service:
      gnetId: 12346
      revision: 1
      datasource: Prometheus

plugins:
  - name: grafana-piechart-panel
    version: latest
  - name: grafana-worldmap-panel
    version: latest
  - name: marcusolsson-csv-datasource
    version: latest

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
  datasources:
    enabled: true
    label: grafana_datasource 