apiVersion: v2
name: money-pulse
description: A Helm chart for Money Pulse finance tracking application
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Your Name
    email: your.email@example.com
dependencies:
  - name: postgresql
    version: ~12.1.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
