# Global values shared across all subcharts
global:
  environment: dev
  registry: ghcr.io
  repositoryOwner: adil-faiyaz98
  imageTag: latest
  domain: money-pulse.local
  postgresql:
    auth:
      username: postgres
      password: postgrespassword
      database: money_pulse

# Parent chart configuration
nameOverride: ""
fullnameOverride: ""

# Subchart configuration
accounts-service:
  enabled: true
  replicaCount: 1
  image:
    repository: "$(global.registry)/$(global.repositoryOwner)/money-pulse/accounts-service"
    tag: "$(global.imageTag)"
  service:
    type: ClusterIP
    httpPort: 80
    grpcPort: 50051
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

users-service:
  enabled: true
  replicaCount: 1
  image:
    repository: "$(global.registry)/$(global.repositoryOwner)/money-pulse/users-service"
    tag: "$(global.imageTag)"
  service:
    type: ClusterIP
    httpPort: 80
    grpcPort: 50052
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

transactions-service:
  enabled: true
  replicaCount: 1
  image:
    repository: "$(global.registry)/$(global.repositoryOwner)/money-pulse/transactions-service"
    tag: "$(global.imageTag)"
  service:
    type: ClusterIP
    httpPort: 80
    grpcPort: 50053
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

postgres:
  enabled: true
  persistence:
    enabled: true
    size: 1Gi
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

replicaCount: 1

image:
  repository: registry.example.com/money-pulse
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: money-pulse.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Database configuration
database:
  host: postgresql
  port: 5432
  name: moneypulse
  user: mpuser

# Account IDs configuration
accounts:
  enabled: true
  # List of account types and their IDs
  types:
    - name: checking
      idPrefix: CHK
    - name: savings
      idPrefix: SAV
    - name: investment
      idPrefix: INV
    - name: credit
      idPrefix: CRD

# Environment-specific configuration
environment: production
logLevel: info

postgresql:
  enabled: true
  auth:
    username: mpuser
    password: ""
    database: moneypulse
  primary:
    persistence:
      size: 8Gi