# Global values shared across all subcharts
global:
  environment: dev
  registry: ghcr.io
  repositoryOwner: adil-faiyaz98
  imageTag: latest
  domain: money-pulse.local
  postgresql:
    auth:
      username: postgres
      password: postgrespassword
      database: money_pulse
  
# Parent chart configuration
nameOverride: ""
fullnameOverride: ""

# Subchart configuration
accounts-service:
  enabled: true
  replicaCount: 1
  image:
    repository: "$(global.registry)/$(global.repositoryOwner)/money-pulse/accounts-service"
    tag: "$(global.imageTag)"
  service:
    type: ClusterIP
    httpPort: 80
    grpcPort: 50051
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

users-service:
  enabled: true
  replicaCount: 1
  image:
    repository: "$(global.registry)/$(global.repositoryOwner)/money-pulse/users-service"
    tag: "$(global.imageTag)"
  service:
    type: ClusterIP
    httpPort: 80
    grpcPort: 50052
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

transactions-service:
  enabled: true
  replicaCount: 1
  image:
    repository: "$(global.registry)/$(global.repositoryOwner)/money-pulse/transactions-service"
    tag: "$(global.imageTag)"
  service:
    type: ClusterIP
    httpPort: 80
    grpcPort: 50053
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

postgres:
  enabled: true
  persistence:
    enabled: true
    size: 1Gi
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: api.$(global.domain)
      paths:
        - path: /accounts/?(.*)
          service: accounts-service
          port: 80
        - path: /users/?(.*)
          service: users-service
          port: 80
        - path: /transactions/?(.*)
          service: transactions-service
          port: 80