global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'aml-service'
    static_configs:
      - targets: ['aml-service:8080']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'kyc-service'
    static_configs:
      - targets: ['kyc-service:8081']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

rule_files:
  - 'rules/*.yml' 