apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyc-service
  namespace: sparkfund
  labels:
    app: kyc-service
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kyc-service
  template:
    metadata:
      labels:
        app: kyc-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: kyc-service
        image: sparkfund/kyc-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: kyc-service-secrets
              key: db-host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: kyc-service-secrets
              key: db-port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: kyc-service-secrets
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kyc-service-secrets
              key: db-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: kyc-service-secrets
              key: db-name
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: kyc-service-secrets
              key: jwt-secret
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: kyc-service-secrets
              key: encryption-key
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: kyc-service-secrets
              key: redis-host
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: kyc-service-secrets
              key: redis-port
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kyc-service-secrets
              key: redis-password
        - name: LOG_LEVEL
          value: "info"
        - name: ENVIRONMENT
          value: "production"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: config
          mountPath: /app/config
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: config
        configMap:
          name: kyc-service-config
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kyc-service
  namespace: sparkfund
spec:
  selector:
    app: kyc-service
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kyc-service-ingress
  namespace: sparkfund
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/rate-limit: "10r/s"
    nginx.ingress.kubernetes.io/rate-limit-burst: "20"
spec:
  tls:
  - hosts:
    - kyc.sparkfund.com
    secretName: kyc-service-tls
  rules:
  - host: kyc.sparkfund.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kyc-service
            port:
              number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kyc-service-config
  namespace: sparkfund
data:
  config.yaml: |
    server:
      port: 8080
      read_timeout: 30s
      write_timeout: 30s
      idle_timeout: 120s
    security:
      rate_limit:
        enabled: true
        requests_per_second: 10
        burst: 20
      cors:
        allowed_origins:
          - https://app.sparkfund.com
        allowed_methods:
          - GET
          - POST
          - PUT
          - DELETE
        allowed_headers:
          - Authorization
          - Content-Type
        max_age: 86400
    logging:
      level: info
      format: json
      output: stdout
    metrics:
      enabled: true
      path: /metrics
    audit:
      enabled: true
      retention_days: 90
      sensitive_fields:
        - password
        - credit_card
        - bank_account
    validation:
      document:
        max_size_mb: 10
        allowed_types:
          - application/pdf
          - image/jpeg
          - image/png
        min_quality: 0.8
      customer:
        min_age: 18
        required_fields:
          - full_name
          - date_of_birth
          - nationality
          - residential_address
          - identification_number
          - tax_id
          - occupation
          - source_of_funds
          - purpose_of_account
    compliance:
      risk_levels:
        low:
          threshold: 10000
          checks:
            - basic_aml
        medium:
          threshold: 50000
          checks:
            - enhanced_aml
            - pep_check
        high:
          threshold: 100000
          checks:
            - comprehensive_aml
            - sanctions_check
            - enhanced_due_diligence
      risk_scoring:
        country_risk: 0.3
        customer_risk: 0.3
        product_risk: 0.2
        transaction_risk: 0.2 