apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: sparkfund
  labels:
    app: user-service
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: user-service
        image: sparkfund/user-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: db-host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: db-port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: db-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: db-name
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: jwt-secret
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: redis-host
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: redis-port
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: redis-password
        - name: LOG_LEVEL
          value: "info"
        - name: ENVIRONMENT
          value: "production"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: config
          mountPath: /app/config
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: config
        configMap:
          name: user-service-config
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: sparkfund
spec:
  selector:
    app: user-service
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-service-ingress
  namespace: sparkfund
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/rate-limit: "10r/s"
    nginx.ingress.kubernetes.io/rate-limit-burst: "20"
spec:
  tls:
  - hosts:
    - users.sparkfund.com
    secretName: user-service-tls
  rules:
  - host: users.sparkfund.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: user-service
            port:
              number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: sparkfund
data:
  config.yaml: |
    server:
      port: 8080
      read_timeout: 30s
      write_timeout: 30s
      idle_timeout: 120s
    security:
      rate_limit:
        enabled: true
        requests_per_second: 10
        burst: 20
      cors:
        allowed_origins:
          - https://app.sparkfund.com
        allowed_methods:
          - GET
          - POST
          - PUT
          - DELETE
        allowed_headers:
          - Authorization
          - Content-Type
        max_age: 86400
      password:
        min_length: 8
        require_uppercase: true
        require_lowercase: true
        require_numbers: true
        require_special: true
        max_age_days: 90
        history_size: 5
    logging:
      level: info
      format: json
      output: stdout
    metrics:
      enabled: true
      path: /metrics
    audit:
      enabled: true
      retention_days: 90
      sensitive_fields:
        - password
        - credit_card
        - bank_account
    session:
      max_duration: 24h
      refresh_interval: 1h
      max_concurrent: 5
    notifications:
      email:
        enabled: true
        templates_dir: /app/templates
      sms:
        enabled: true
        provider: twilio
    cache:
      ttl: 1h
      max_size: 1000 