replicaCount: 1

nameOverride: ""
fullnameOverride: ""

image:
  repository: your-registry/loans
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []

podSecurityContext: {}

securityContext: {}

serviceAccount:
  create: true
  name: ""

podAnnotations: {}

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
  scaleUpCooldownPeriod: 180
  scaleDownCooldownPeriod: 180

nodeSelector: {}

tolerations: []

affinity: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

env:
  - name: DB_HOST
    value: "postgres"
  - name: DB_PORT
    value: "5432"
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: loans-db-secret
        key: username
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: loans-db-secret
        key: password
  - name: DB_NAME
    valueFrom:
      secretKeyRef:
        name: loans-db-secret
        key: database 