apiVersion: v2
name: kyc-service
description: A Helm chart for the KYC Service
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
