version: "3.8"
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: investment_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  investment-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: investment_db
    depends_on:
      - db

volumes:
  db_data: