apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- secret.yaml

commonLabels:
  app.kubernetes.io/name: accounts-service
  app.kubernetes.io/part-of: money-pulse 