apiVersion: v1
kind: Secret
metadata:
  name: accounts-service-secrets
type: Opaque
data:
  # Base64 encoded database DSN
  db-dsn: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3JlcyQxMC4wLjEwLjEwMC9tb25leV9wdWxzZT9zc2xtb2RlPWRpc2FibGU= 