apiVersion: v1
kind: Secret
metadata:
  name: user-service-db-credentials
  namespace: sparkfund
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres
  password: cGFzc3dvcmQ=  # password

---
apiVersion: v1
kind: Secret
metadata:
  name: user-service-jwt
  namespace: sparkfund
type: Opaque
data:
  secret: c2VjcmV0LWtleS1mb3ItcHJvZHVjdGlvbg==  # secret-key-for-production

---
apiVersion: v1
kind: Secret
metadata:
  name: user-service-redis
  namespace: sparkfund
type: Opaque
data:
  password: cmVkaXMtcGFzc3dvcmQ=  # redis-password
