clusterName: elasticsearch
nodeGroup: master

roles: ["master", "data"]

replicas: 3

minimumMasterNodes: 2

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 1
    memory: 2Gi

volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "standard"
  resources:
    requests:
      storage: 100Gi

config:
  node.store.allow_mmap: false
  cluster.name: elasticsearch
  network.host: 0.0.0.0
  discovery.type: single-node
  xpack.security.enabled: true
  xpack.monitoring.enabled: true
  xpack.monitoring.elasticsearch.collection.enabled: true

extraEnvs:
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elasticsearch
        key: password

service:
  type: ClusterIP
  ports:
    - name: http
      port: 9200
      targetPort: 9200
    - name: transport
      port: 9300
      targetPort: 9300

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - elasticsearch.sparkfund.com
  tls:
    - secretName: elasticsearch-tls
      hosts:
        - elasticsearch.sparkfund.com 