global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8080']

  - job_name: 'account-service'
    static_configs:
      - targets: ['account-service:8081']

  - job_name: 'transaction-service'
    static_configs:
      - targets: ['transaction-service:8082']
      
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8085']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
