apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kyc-service
  namespace: sparkfund
  labels:
    app: kyc-service
    release: prometheus
spec:
  selector:
    matchLabels:
      app: kyc-service
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
  namespaceSelector:
    matchNames:
    - sparkfund
