apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kyc-service-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: kyc-service
  endpoints:
  - port: http
    interval: 15s
    path: /metrics 