apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-notifications
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: sparkfund
  
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 1.8.1
    chart: argocd-notifications
    helm:
      values: |
        notifiers:
          service.slack: |
            token: $slack-token
            username: ArgoCD
            icon: https://argocd-notifications.readthedocs.io/en/stable/assets/logo.png
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
