apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: allInOne
  storage:
    type: memory
    options:
      memory:
        max-traces: 100000
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - jaeger.sparkfund.com
  service:
    type: ClusterIP
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  options:
    log-level: debug
    service:
      metrics:
        storage:
          type: prometheus
          options:
            prometheus:
              server-url: http://prometheus:9090
    storage:
      type: memory
      options:
        memory:
          max-traces: 100000
    dependencies:
      enabled: true
    kafka:
      producer:
        topic: jaeger-spans
      consumer:
        topic: jaeger-spans
    collector:
      zipkin:
        host-port: :9411
    query:
      base-path: /jaeger
      static-files: /usr/share/jaeger/html
    agent:
      options:
        log-level: debug
    ui:
      options:
        dependencies:
          menuEnabled: true
        tracking:
          gaID: UA-000000-2
        menu:
          - label: "About Jaeger"
            items:
              - label: "Documentation"
                url: "https://www.jaegertracing.io/docs/latest"
              - label: "GitHub"
                url: "https://github.com/jaegertracing/jaeger" 