# Default values for investment-service
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: ghcr.io/adil-faiyaz98/sparkfund/investment-service
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 8080
  annotations: {}

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/rate-limit: "10r/s"
    nginx.ingress.kubernetes.io/rate-limit-burst: "20"
  hosts:
    - host: investment.sparkfund.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: investment-service-tls
      hosts:
        - investment.sparkfund.com

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

podDisruptionBudget:
  enabled: true
  minAvailable: 2

nodeSelector: {}

tolerations: []

affinity: {}

env:
  environment: production
  logLevel: info
  logFormat: json

metrics:
  enabled: true
  port: 8080
  path: /metrics

tracing:
  enabled: true
  endpoint: http://jaeger-collector.monitoring:14268/api/traces
  samplingRate: "0.1"

database:
  enabled: true
  sslMode: require

cache:
  enabled: true
  type: redis

jwt:
  enabled: true
  expiry: 24h

config:
  enabled: true
  data:
    config.yaml: |
      server:
        port: 8080
        read_timeout: 30s
        write_timeout: 30s
        idle_timeout: 120s
      security:
        rate_limit:
          enabled: true
          requests_per_second: 10
          burst: 20
        cors:
          allowed_origins:
            - https://app.sparkfund.com
          allowed_methods:
            - GET
            - POST
            - PUT
            - DELETE
          allowed_headers:
            - Authorization
            - Content-Type
          max_age: 86400
      logging:
        level: info
        format: json
        output: stdout
      metrics:
        enabled: true
        path: /metrics
      audit:
        enabled: true
        retention_days: 90
        sensitive_fields:
          - password
          - credit_card
          - bank_account

probes:
  liveness:
    path: /health/live
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    path: /health/ready
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

deployment:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

networkPolicy:
  enabled: true
  ingress:
    from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: api-gateway
      - namespaceSelector:
          matchLabels:
            name: monitoring
        podSelector:
          matchLabels:
            app: prometheus
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 5432  # PostgreSQL
        - protocol: TCP
          port: 6379  # Redis
        - protocol: TCP
          port: 9411  # Zipkin
        - protocol: TCP
          port: 14268 # Jaeger

extraVolumes:
  - name: investments
    persistentVolumeClaim:
      claimName: investment-uploads-pvc

extraVolumeMounts:
  - name: investments
    mountPath: /data/investments
