apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - prometheus/
  - grafana/
  - jaeger/
  - elasticsearch/

commonLabels:
  app.kubernetes.io/part-of: observability
  app.kubernetes.io/managed-by: kustomize 