apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sparkfund-ingress
  namespace: sparkfund
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
spec:
  tls:
    - hosts:
        - api.sparkfund.local
  rules:
    - host: api.sparkfund.local
      http:
        paths:
          - path: /api/v1/users
            pathType: Prefix
            backend:
              service:
                name: users-service
                port:
                  number: 8080
          - path: /api/v1/accounts
            pathType: Prefix
            backend:
              service:
                name: accounts-service
                port:
                  number: 8080
          - path: /api/v1/transactions
            pathType: Prefix
            backend:
              service:
                name: transactions-service
                port:
                  number: 8080
          - path: /api/v1/investments
            pathType: Prefix
            backend:
              service:
                name: investments-service
                port:
                  number: 8080
          - path: /api/v1/loans
            pathType: Prefix
            backend:
              service:
                name: loans-service
                port:
                  number: 8080
          - path: /api/v1/reports
            pathType: Prefix
            backend:
              service:
                name: reports-service
                port:
                  number: 8080
          - path: /api/v1/auth
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 8080
  # TLS configuration - uncomment for production
  # tls:
  # - hosts:
  #   - api.money-pulse.local
  #   secretName: money-pulse-tls