{{- define "common.istio-gateway" -}}
{{- if .Values.istio.gateway.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway
  servers:
    {{- range .Values.istio.gateway.servers }}
    - port:
        number: {{ .port.number }}
        name: {{ .port.name }}
        protocol: {{ .port.protocol }}
      hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      {{- if .tls }}
      tls:
        mode: {{ .tls.mode }}
        {{- if .tls.credentialName }}
        credentialName: {{ .tls.credentialName }}
        {{- end }}
        {{- if .tls.serverCertificate }}
        serverCertificate: {{ .tls.serverCertificate }}
        {{- end }}
        {{- if .tls.privateKey }}
        privateKey: {{ .tls.privateKey }}
        {{- end }}
        {{- if .tls.caCertificates }}
        caCertificates: {{ .tls.caCertificates }}
        {{- end }}
        {{- if .tls.subjectAltNames }}
        subjectAltNames:
          {{- range .tls.subjectAltNames }}
          - {{ . | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
{{- end }}
{{- end -}}
