{{- define "common.istio-peerauthentication" -}}
{{- if .Values.istio.peerAuthentication.enabled -}}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  mtls:
    mode: {{ .Values.istio.peerAuthentication.mtls.mode }}
  {{- if .Values.istio.peerAuthentication.portLevelMtls }}
  portLevelMtls:
    {{- range $port, $mode := .Values.istio.peerAuthentication.portLevelMtls }}
    {{ $port }}:
      mode: {{ $mode }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end -}}
