{{- define "common.limitrange" -}}
{{- if .Values.limitRange.enabled -}}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "common.fullname" . }}-limit-range
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  limits:
    - type: Container
      default:
        {{- if .Values.limitRange.default.cpu }}
        cpu: {{ .Values.limitRange.default.cpu }}
        {{- end }}
        {{- if .Values.limitRange.default.memory }}
        memory: {{ .Values.limitRange.default.memory }}
        {{- end }}
      defaultRequest:
        {{- if .Values.limitRange.defaultRequest.cpu }}
        cpu: {{ .Values.limitRange.defaultRequest.cpu }}
        {{- end }}
        {{- if .Values.limitRange.defaultRequest.memory }}
        memory: {{ .Values.limitRange.defaultRequest.memory }}
        {{- end }}
      {{- if or .Values.limitRange.max.cpu .Values.limitRange.max.memory }}
      max:
        {{- if .Values.limitRange.max.cpu }}
        cpu: {{ .Values.limitRange.max.cpu }}
        {{- end }}
        {{- if .Values.limitRange.max.memory }}
        memory: {{ .Values.limitRange.max.memory }}
        {{- end }}
      {{- end }}
      {{- if or .Values.limitRange.min.cpu .Values.limitRange.min.memory }}
      min:
        {{- if .Values.limitRange.min.cpu }}
        cpu: {{ .Values.limitRange.min.cpu }}
        {{- end }}
        {{- if .Values.limitRange.min.memory }}
        memory: {{ .Values.limitRange.min.memory }}
        {{- end }}
      {{- end }}
{{- end }}
{{- end -}}
