{{- define "common.networkpolicy-enhanced" -}}
{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow traffic from API Gateway
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: api-gateway
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
    # Allow traffic from Prometheus for metrics scraping
    - from:
        - namespaceSelector:
            matchLabels:
              name: monitoring
          podSelector:
            matchLabels:
              app: prometheus
      ports:
        - protocol: TCP
          port: {{ .Values.metrics.port | default 8080 }}
    # Allow traffic from other services in the same namespace if specified
    {{- if .Values.networkPolicy.allowSameNamespace }}
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
    {{- end }}
    # Allow traffic from specific services if specified
    {{- range .Values.networkPolicy.additionalAllowedServices }}
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ . }}
      ports:
        - protocol: TCP
          port: {{ $.Values.service.port }}
    {{- end }}
  egress:
    # Allow DNS resolution
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow traffic to PostgreSQL
    {{- if .Values.database.enabled }}
    - to:
        - podSelector:
            matchLabels:
              app: postgres
      ports:
        - protocol: TCP
          port: 5432
    {{- end }}
    # Allow traffic to Redis
    {{- if .Values.cache.enabled }}
    - to:
        - podSelector:
            matchLabels:
              app: redis
      ports:
        - protocol: TCP
          port: 6379
    {{- end }}
    # Allow traffic to specific services if specified
    {{- range .Values.networkPolicy.additionalAllowedEgress }}
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ .service }}
      ports:
        - protocol: TCP
          port: {{ .port }}
    {{- end }}
    # Allow traffic to external services if specified
    {{- if .Values.networkPolicy.allowExternal }}
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 443
    {{- end }}
{{- end }}
{{- end -}}
