{{- define "common.preview-service" -}}
{{- if and .Values.rollout.enabled (eq .Values.rollout.strategy.type "BlueGreen") -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}-preview
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: preview
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port | default 8080 }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
{{- end }}
{{- end -}}
