apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - configmap.yaml
  - secrets.yaml

commonLabels:
  app.kubernetes.io/name: users-service
  app.kubernetes.io/part-of: money-pulse
  app.kubernetes.io/managed-by: kustomize
  environment: development 