apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: api-gateway
  namespace: sparkfund
spec:
  # Deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway
  # HPA reference (optional)
  autoscalerRef:
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    name: api-gateway
  # The service mesh provider
  provider: istio
  # Service mesh specific settings
  service:
    # Container port
    port: 8080
    # Istio gateways (optional)
    gateways:
    - public-gateway.istio-system.svc.cluster.local
    # Istio virtual service host names (optional)
    hosts:
    - api.sparkfund.com
    # Istio traffic policy (optional)
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
  # Define the canary analysis timing and KPIs
  analysis:
    # Schedule interval (default 60s)
    interval: 1m
    # Max number of failed metric checks before rollback
    threshold: 5
    # Max traffic percentage routed to canary
    maxWeight: 50
    # Canary increment step
    stepWeight: 10
    # Prometheus metrics
    metrics:
    - name: request-success-rate
      # Minimum req success rate (http 2xx/3xx responses)
      thresholdRange:
        min: 99
      interval: 1m
    - name: request-duration
      # Maximum req duration P99
      thresholdRange:
        max: 500
      interval: 1m
    # A/B Testing - HTTP headers match conditions
    match:
      - headers:
          x-canary:
            exact: "true"
      - headers:
          cookie:
            regex: "^(.*?;)?(canary=true)(;.*)?$"
    # Webhook for load testing
    webhooks:
      - name: load-test
        url: http://flagger-loadtester.sparkfund/
        timeout: 5s
        metadata:
          cmd: "hey -z 1m -q 10 -c 2 http://api-gateway.sparkfund:8080/"
      - name: prometheus-alerts
        url: http://prometheus-alertmanager.monitoring:9093/api/v1/alerts
        timeout: 5s
