apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: sparkfund
data:
  config.yaml: |
    app:
      name: api-gateway
      environment: production
      log_level: info
      metrics_enabled: true
      tracing_enabled: true
      rate_limit:
        enabled: true
        requests_per_second: 1000
        burst_size: 2000
      security:
        cors:
          allowed_origins: ["https://api.sparkfund.com", "https://app.sparkfund.com"]
          allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
          allowed_headers: ["Authorization", "Content-Type", "X-Request-ID"]
          max_age: 3600
        headers:
          x_frame_options: "DENY"
          x_content_type_options: "nosniff"
          x_xss_protection: "1; mode=block"
          strict_transport_security: "max-age=31536000; includeSubDomains"
          content_security_policy: "default-src 'self'"
    
    services:
      auth:
        url: "http://auth-service.sparkfund.svc.cluster.local:8080"
        timeout: 5
      kyc:
        url: "http://kyc-service.sparkfund.svc.cluster.local:8080"
        timeout: 5
      aml:
        url: "http://aml-service.sparkfund.svc.cluster.local:8080"
        timeout: 5
      credit_scoring:
        url: "http://credit-scoring-service.sparkfund.svc.cluster.local:8080"
        timeout: 5
      investment:
        url: "http://investment-service.sparkfund.svc.cluster.local:8080"
        timeout: 5
    
    routes:
      - path: "/api/v1/auth"
        service: auth
        methods: ["POST", "GET"]
        rate_limit:
          requests_per_second: 100
          burst_size: 200
      - path: "/api/v1/kyc"
        service: kyc
        methods: ["POST", "GET"]
        rate_limit:
          requests_per_second: 50
          burst_size: 100
      - path: "/api/v1/aml"
        service: aml
        methods: ["POST", "GET"]
        rate_limit:
          requests_per_second: 50
          burst_size: 100
      - path: "/api/v1/credit-scoring"
        service: credit_scoring
        methods: ["POST", "GET"]
        rate_limit:
          requests_per_second: 50
          burst_size: 100
      - path: "/api/v1/investment"
        service: investment
        methods: ["POST", "GET", "PUT", "DELETE"]
        rate_limit:
          requests_per_second: 200
          burst_size: 400
    
    monitoring:
      enabled: true
      prometheus:
        enabled: true
        path: /metrics
        port: 9090
      health:
        enabled: true
        path: /health
        port: 8081
      tracing:
        enabled: true
        sampler: 1.0
        exporter:
          type: jaeger
          endpoint: jaeger.sparkfund.svc.cluster.local:14268
          service_name: api-gateway
    
    cache:
      enabled: true
      ttl: 300
      max_size: 1000
    
    circuit_breaker:
      enabled: true
      failure_threshold: 5
      reset_timeout: 60
      half_open_timeout: 30
    
    retry:
      enabled: true
      max_attempts: 3
      initial_interval: 100
      max_interval: 1000
      multiplier: 2 