apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secrets
  namespace: sparkfund
  annotations:
    kubernetes.io/service-account.name: api-gateway
type: Opaque
stringData:
  # JWT configuration
  jwt_secret: "REPLACE_WITH_JWT_SECRET"
  jwt_issuer: "sparkfund-api-gateway"
  jwt_audience: "sparkfund-services"
  jwt_expiry: "3600"
  
  # API keys for external services
  auth_service_api_key: "REPLACE_WITH_AUTH_SERVICE_API_KEY"
  kyc_service_api_key: "REPLACE_WITH_KYC_SERVICE_API_KEY"
  aml_service_api_key: "REPLACE_WITH_AML_SERVICE_API_KEY"
  credit_scoring_service_api_key: "REPLACE_WITH_CREDIT_SCORING_SERVICE_API_KEY"
  investment_service_api_key: "REPLACE_WITH_INVESTMENT_SERVICE_API_KEY"
  
  # Encryption keys
  encryption_key: "REPLACE_WITH_ENCRYPTION_KEY"
  encryption_iv: "REPLACE_WITH_ENCRYPTION_IV"
  
  # Rate limiting keys
  rate_limit_key: "REPLACE_WITH_RATE_LIMIT_KEY"
  
  # Monitoring credentials
  prometheus_basic_auth: "REPLACE_WITH_PROMETHEUS_BASIC_AUTH"
  
  # SSL certificates
  ssl_cert: |
    -----BEGIN CERTIFICATE-----
    Your SSL certificate here
    -----END CERTIFICATE-----
  ssl_key: |
    -----BEGIN PRIVATE KEY-----
    Your SSL key here
    -----END PRIVATE KEY-----
  
  # Additional security keys
  session_key: "REPLACE_WITH_SESSION_KEY"
  csrf_key: "REPLACE_WITH_CSRF_KEY"
  
  # External service credentials
  external_auth_provider_key: "REPLACE_WITH_EXTERNAL_AUTH_PROVIDER_KEY"
  external_auth_provider_secret: "REPLACE_WITH_EXTERNAL_AUTH_PROVIDER_SECRET"
  
  # Grafana basic authentication
  grafana_basic_auth: "admin:your-grafana-password" 