apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-service
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: accounts-service
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi 