apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-uploads-pvc
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
