apiVersion: v1
kind: Secret
metadata:
  name: investment-service-secrets
  namespace: sparkfund
  annotations:
    kubernetes.io/service-account.name: investment-service
type: Opaque
stringData:
  # Database credentials
  db_password: "REPLACE_WITH_DB_PASSWORD"
  db_user: "REPLACE_WITH_DB_USER"
  
  # Redis credentials
  redis_password: "REPLACE_WITH_REDIS_PASSWORD"
  
  # External trading API credentials
  trading_api_key: "REPLACE_WITH_TRADING_API_KEY"
  trading_api_secret: "REPLACE_WITH_TRADING_API_SECRET"
  market_data_api_key: "REPLACE_WITH_MARKET_DATA_API_KEY"
  market_data_api_secret: "REPLACE_WITH_MARKET_DATA_API_SECRET"
  
  # Model configuration
  model_encryption_key: "REPLACE_WITH_MODEL_ENCRYPTION_KEY"
  model_encryption_iv: "REPLACE_WITH_MODEL_ENCRYPTION_IV"
  model_version: "1.0.0"
  
  # Encryption keys
  encryption_key: "REPLACE_WITH_ENCRYPTION_KEY"
  encryption_iv: "REPLACE_WITH_ENCRYPTION_IV"
  
  # External service credentials
  trading_platform_api_url: "https://trading-platform-api.example.com"
  market_data_api_url: "https://market-data-api.example.com"
  compliance_api_key: "REPLACE_WITH_COMPLIANCE_API_KEY"
  compliance_api_secret: "REPLACE_WITH_COMPLIANCE_API_SECRET"
  
  # Monitoring credentials
  prometheus_basic_auth: "REPLACE_WITH_PROMETHEUS_BASIC_AUTH"
  
  # Additional security keys
  rate_limit_key: "REPLACE_WITH_RATE_LIMIT_KEY"
  session_key: "REPLACE_WITH_SESSION_KEY"
  csrf_key: "REPLACE_WITH_CSRF_KEY"

  # SSL certificates
  db_ssl_cert: |
    -----BEGIN CERTIFICATE-----
    Your SSL certificate here
    -----END CERTIFICATE-----
  db_ssl_key: |
    -----BEGIN PRIVATE KEY-----
    Your SSL key here
    -----END PRIVATE KEY-----

  # Redis SSL certificates
  redis_ssl_cert: |
    -----BEGIN CERTIFICATE-----
    Your Redis SSL certificate here
    -----END CERTIFICATE-----

  # External service URLs
  trading_platform_api_url: "https://trading-platform-api.example.com"
  market_data_api_url: "https://market-data-api.example.com"
  compliance_api_url: "https://compliance-api.example.com"

  # Grafana basic authentication
  grafana_basic_auth: "admin:your-grafana-password" 