apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: money-pulse-dev

resources:
  - ../../base

patches:
  - path: patches/replica-count.yaml
  - path: patches/resource-limits.yaml
  - path: patches/ingress.yaml

configMapGenerator:
  - name: moneypulse-config
    behavior: merge
    literals:
      - environment=development
      - log_level=debug
      - tracing_enabled=false

commonLabels:
  environment: development 