version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    container_name: user-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_service
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: .
      target: production
    container_name: user-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      APP_ENV: production
      APP_DATABASE_HOST: postgres
      APP_DATABASE_PORT: 5432
      APP_DATABASE_USER: postgres
      APP_DATABASE_PASSWORD: postgres
      APP_DATABASE_NAME: user_service
      APP_DATABASE_SSLMODE: disable
      APP_JWT_SECRET: your-jwt-secret
    ports:
      - "8084:8084"
    volumes:
      - ./uploads:/data/users
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8084/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  postgres_data:
