apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: users-service
        env:
        - name: LOG_LEVEL
          value: debug
        - name: TRACING_SAMPLER
          value: "1.0"
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "256Mi" 