openapi: 3.0.0
info:
  title: Credit Scoring Service API
  description: API for credit scoring and credit history management
  version: 1.0.0
  contact:
    name: SparkFund Team
    email: support@sparkfund.com

servers:
  - url: http://localhost:8080
    description: Local development server
  - url: https://api.sparkfund.com
    description: Production server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    CreditCheckRequest:
      type: object
      required:
        - user_id
        - account_type
        - institution
        - credit_limit
        - current_balance
        - open_date
      properties:
        user_id:
          type: string
          format: uuid
          description: Unique identifier of the user
        account_type:
          type: string
          enum: [credit_card, loan, mortgage, line_of_credit]
          description: Type of credit account
        institution:
          type: string
          description: Name of the financial institution
        account_number:
          type: string
          description: Account number (masked)
        credit_limit:
          type: number
          format: float
          description: Credit limit of the account
        current_balance:
          type: number
          format: float
          description: Current balance of the account
        open_date:
          type: string
          format: date
          description: Date when the account was opened
        close_date:
          type: string
          format: date
          description: Date when the account was closed (if applicable)
        last_payment_date:
          type: string
          format: date
          description: Date of the last payment
        last_payment_amount:
          type: number
          format: float
          description: Amount of the last payment

    CreditScoreResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier of the credit score
        user_id:
          type: string
          format: uuid
          description: Unique identifier of the user
        score:
          type: integer
          minimum: 300
          maximum: 850
          description: Credit score value
        score_range:
          type: string
          enum: [excellent, very_good, good, fair, poor]
          description: Credit score range category
        last_updated:
          type: string
          format: date-time
          description: Last update timestamp
        factors:
          type: array
          items:
            type: string
          description: Factors affecting the credit score
        recommendations:
          type: array
          items:
            type: string
          description: Recommendations for improving credit score
        created_at:
          type: string
          format: date-time
          description: Creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp

    CreditHistoryResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier of the credit history
        user_id:
          type: string
          format: uuid
          description: Unique identifier of the user
        account_type:
          type: string
          enum: [credit_card, loan, mortgage, line_of_credit]
          description: Type of credit account
        institution:
          type: string
          description: Name of the financial institution
        account_number:
          type: string
          description: Account number (masked)
        status:
          type: string
          enum: [active, closed, defaulted]
          description: Current status of the account
        credit_limit:
          type: number
          format: float
          description: Credit limit of the account
        current_balance:
          type: number
          format: float
          description: Current balance of the account
        payment_history:
          type: array
          items:
            type: object
            properties:
              date:
                type: string
                format: date
                description: Payment date
              amount:
                type: number
                format: float
                description: Payment amount
              status:
                type: string
                enum: [on_time, late, missed]
                description: Payment status
        open_date:
          type: string
          format: date
          description: Date when the account was opened
        close_date:
          type: string
          format: date
          description: Date when the account was closed (if applicable)
        last_payment_date:
          type: string
          format: date
          description: Date of the last payment
        last_payment_amount:
          type: number
          format: float
          description: Amount of the last payment
        created_at:
          type: string
          format: date-time
          description: Creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message

paths:
  /api/v1/credit/check:
    post:
      summary: Process a credit check request
      description: Submit a new credit check request for processing
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreditCheckRequest'
      responses:
        '200':
          description: Credit check processed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditHistoryResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/credit/score/{user_id}:
    get:
      summary: Get credit score
      description: Retrieve the credit score for a specific user
      security:
        - bearerAuth: []
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Unique identifier of the user
      responses:
        '200':
          description: Credit score retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditScoreResponse'
        '400':
          description: Invalid user ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Credit score not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/credit/history/{user_id}:
    get:
      summary: Get credit history
      description: Retrieve the credit history for a specific user
      security:
        - bearerAuth: []
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Unique identifier of the user
      responses:
        '200':
          description: Credit history retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CreditHistoryResponse'
        '400':
          description: Invalid user ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/credit/history/{id}/status:
    put:
      summary: Update credit history status
      description: Update the status of a credit history record
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Unique identifier of the credit history
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - status
              properties:
                status:
                  type: string
                  enum: [active, closed, defaulted]
                  description: New status of the credit history
      responses:
        '200':
          description: Credit history status updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Success message
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Credit history not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error' 