apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "accounts-service.fullname" . }}-config
  labels:
    {{- include "accounts-service.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  ENVIRONMENT: {{ .Values.config.environment | quote }}
  HTTP_PORT: {{ .Values.config.httpPort | quote }}
  GRPC_PORT: {{ .Values.config.grpcPort | quote }}