global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
  - job_name: 'kyc-service'
    static_configs:
      - targets: ['kyc-service:8081']
  - job_name: 'investment-service'
    static_configs:
      - targets: ['investment-service:8082']
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8083']
  - job_name: 'ai-service'
    static_configs:
      - targets: ['ai-service:8001']
