apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "kyc-service.labels" . | nindent 4 }}
data:
  config.yaml: |
    app:
      name: {{ .Chart.Name }}
      version: {{ .Chart.AppVersion }}
      environment: {{ .Values.environment }}
    
    server:
      port: 8080
      timeout: {{ .Values.server.timeout }}

    ai:
      models:
        {{- toYaml .Values.ai.models | nindent 8 }}