apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kyc-service.fullname" . }}-config
  labels:
    {{- include "kyc-service.labels" . | nindent 4 }}
data:
  config.yaml: |
    server:
      port: {{ .Values.config.server.port | quote }}
      shutdownTimeout: {{ .Values.config.server.shutdownTimeout }}
    database:
      host: {{ .Values.config.database.host }}
      port: {{ .Values.config.database.port | quote }}
      name: {{ .Values.config.database.name }}
      user: {{ .Values.config.database.user }}
      sslMode: {{ .Values.config.database.sslMode }}
    log:
      level: {{ .Values.config.log.level }}
      format: {{ .Values.config.log.format }}
    metrics:
      enabled: {{ .Values.config.metrics.enabled | quote }}
      port: {{ .Values.config.metrics.port | quote }}
      path: {{ .Values.config.metrics.path }}
    security:
      jwtExpiry: {{ .Values.config.security.jwtExpiry }}
      cors:
        allowedOrigins: {{ toJson .Values.config.security.cors.allowedOrigins }}
        allowedMethods: {{ toJson .Values.config.security.cors.allowedMethods }}
        allowedHeaders: {{ toJson .Values.config.security.cors.allowedHeaders }}
    elasticsearch:
      url: {{ .Values.config.elasticsearch.url }}
      indexPrefix: {{ .Values.config.elasticsearch.indexPrefix }}
    jaeger:
      endpoint: {{ .Values.config.jaeger.endpoint }}
      samplingRate: {{ .Values.config.jaeger.samplingRate | quote }} 