global:
  environment: development
  domain: sparkfund.local
  registry: ghcr.io
  repositoryOwner: adil-faiyaz98

accounts:
  name: accounts-service
  image:
    repository: "$(global.registry)/$(global.repositoryOwner)/sparkfund/accounts-service"
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "300m"
  env:
    - name: APP_ENV
      value: development
    - name: LOG_LEVEL
      value: debug
    - name: SERVER_PORT
      value: "8080"
    - name: DB_HOST
      value: postgres
    - name: DB_PORT
      value: "5432"
    - name: DB_NAME
      value: sparkfund
    - name: DB_SSL_MODE
      value: disable

users:
  name: users-service
  image:
    repository: "$(global.registry)/$(global.repositoryOwner)/sparkfund/users-service"
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "300m"
  env:
    - name: APP_ENV
      value: development
    - name: LOG_LEVEL
      value: debug
    - name: SERVER_PORT
      value: "8080"
    - name: DB_HOST
      value: postgres
    - name: DB_PORT
      value: "5432"
    - name: DB_NAME
      value: sparkfund
    - name: DB_SSL_MODE
      value: disable

transactions:
  name: transactions-service
  image:
    repository: "$(global.registry)/$(global.repositoryOwner)/sparkfund/transactions-service"
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "300m"
  env:
    - name: APP_ENV
      value: development
    - name: LOG_LEVEL
      value: debug
    - name: SERVER_PORT
      value: "8080"
    - name: DB_HOST
      value: postgres
    - name: DB_PORT
      value: "5432"
    - name: DB_NAME
      value: sparkfund
    - name: DB_SSL_MODE
      value: disable

postgres:
  name: postgres
  image:
    repository: postgres
    tag: 15-alpine
  service:
    type: ClusterIP
    port: 5432
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  persistence:
    size: 10Gi
    accessMode: ReadWriteOnce
  env:
    - name: POSTGRES_DB
      value: sparkfund
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: username
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: password

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
  hosts:
    - host: sparkfund.local
      paths:
        - path: /api/v1/users
          pathType: Prefix
          service: users-service
          port: 8080
        - path: /api/v1/accounts
          pathType: Prefix
          service: accounts-service
          port: 8080
        - path: /api/v1/transactions
          pathType: Prefix
          service: transactions-service
          port: 8080 