apiVersion: v1
kind: Secret
metadata:
  name: aml-service-secrets
  namespace: sparkfund
  annotations:
    kubernetes.io/service-account.name: aml-service
type: Opaque
stringData:
  # Database credentials
  db_password: "REPLACE_WITH_DB_PASSWORD"
  db_user: "REPLACE_WITH_DB_USER"
  
  # Redis credentials
  redis_password: "REPLACE_WITH_REDIS_PASSWORD"
  
  # JWT configuration
  jwt_secret: "REPLACE_WITH_JWT_SECRET"
  jwt_issuer: "sparkfund-aml-service"
  jwt_audience: "sparkfund-clients"
  jwt_expiry: "24h"
  
  # API keys for external services
  aml_api_key: "REPLACE_WITH_AML_API_KEY"
  aml_api_secret: "REPLACE_WITH_AML_API_SECRET"
  
  # Encryption keys
  encryption_key: "REPLACE_WITH_ENCRYPTION_KEY"
  encryption_iv: "REPLACE_WITH_ENCRYPTION_IV"
  
  # External service credentials
  external_aml_provider_key: "REPLACE_WITH_EXTERNAL_AML_PROVIDER_KEY"
  external_aml_provider_secret: "REPLACE_WITH_EXTERNAL_AML_PROVIDER_SECRET"
  
  # Monitoring credentials
  prometheus_basic_auth: "REPLACE_WITH_PROMETHEUS_BASIC_AUTH"
  
  # Additional security keys
  rate_limit_key: "REPLACE_WITH_RATE_LIMIT_KEY"
  session_key: "REPLACE_WITH_SESSION_KEY"

  # SSL certificates
  db_ssl_cert: |
    -----BEGIN CERTIFICATE-----
    Your SSL certificate here
    -----END CERTIFICATE-----
  db_ssl_key: |
    -----BEGIN PRIVATE KEY-----
    Your SSL key here
    -----END PRIVATE KEY-----

  # Redis SSL certificates
  redis_ssl_cert: |
    -----BEGIN CERTIFICATE-----
    Your Redis SSL certificate here
    -----END CERTIFICATE-----

  # AML API endpoint
  aml_api_endpoint: "https://aml-provider-api.example.com"

  # External service URL
  external_api_url: "https://external-service.example.com"

  # Grafana basic authentication
  grafana_basic_auth: "admin:your-grafana-password" 