apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: sparkfund
data:
  config.yaml: |
    app:
      name: auth-service
      environment: production
      log_level: info
      metrics_enabled: true
      tracing_enabled: true
      rate_limit:
        enabled: true
        requests_per_second: 100
        burst_size: 200
      security:
        cors:
          allowed_origins: ["https://api.sparkfund.com"]
          allowed_methods: ["GET", "POST", "PUT", "DELETE"]
          allowed_headers: ["Authorization", "Content-Type"]
          max_age: 3600
        headers:
          x_frame_options: "DENY"
          x_content_type_options: "nosniff"
          x_xss_protection: "1; mode=block"
          strict_transport_security: "max-age=31536000; includeSubDomains"
          content_security_policy: "default-src 'self'"
    
    database:
      host: postgres.sparkfund.svc.cluster.local
      port: 5432
      name: sparkfund
      ssl_mode: require
      max_connections: 20
      idle_timeout: 300
      connection_timeout: 10
    
    redis:
      host: redis.sparkfund.svc.cluster.local
      port: 6379
      password: ""
      db: 0
      pool_size: 10
      min_idle_conns: 5
      idle_timeout: 300
    
    auth:
      jwt:
        issuer: sparkfund-auth-service
        audience: sparkfund-clients
        expiry: 24h
        refresh_expiry: 168h
      session:
        max_age: 24h
        secure: true
        http_only: true
        same_site: strict
      password:
        min_length: 12
        require_special: true
        require_numbers: true
        require_uppercase: true
        require_lowercase: true
      mfa:
        enabled: true
        methods: ["totp", "sms"]
        backup_codes_count: 8
    
    tracing:
      enabled: true
      sampler: 1.0
      exporter:
        type: jaeger
        endpoint: jaeger.sparkfund.svc.cluster.local:14268
        service_name: auth-service
    
    monitoring:
      enabled: true
      prometheus:
        enabled: true
        path: /metrics
        port: 9090
      health:
        enabled: true
        path: /health
        port: 8081 