apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sparkfund

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml

commonLabels:
  app.kubernetes.io/name: auth-service
  app.kubernetes.io/part-of: sparkfund
  app.kubernetes.io/managed-by: kustomize 