apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: sparkfund
  annotations:
    kubernetes.io/service-account.name: auth-service
type: Opaque
stringData:
  # Database credentials
  db_password: "REPLACE_WITH_DB_PASSWORD"
  db_user: "REPLACE_WITH_DB_USER"
  
  # Redis credentials
  redis_password: "REPLACE_WITH_REDIS_PASSWORD"
  
  # JWT configuration
  jwt_secret: "REPLACE_WITH_JWT_SECRET"
  jwt_issuer: "sparkfund-auth-service"
  jwt_audience: "sparkfund-clients"
  jwt_expiry: "24h"
  jwt_refresh_secret: "REPLACE_WITH_JWT_REFRESH_SECRET"
  jwt_refresh_expiry: "168h"
  
  # OAuth credentials
  oauth_client_id: "REPLACE_WITH_OAUTH_CLIENT_ID"
  oauth_client_secret: "REPLACE_WITH_OAUTH_CLIENT_SECRET"
  oauth_redirect_uri: "https://api.sparkfund.com/auth/callback"
  
  # Encryption keys
  encryption_key: "REPLACE_WITH_ENCRYPTION_KEY"
  encryption_iv: "REPLACE_WITH_ENCRYPTION_IV"
  
  # External service credentials
  sms_provider_key: "REPLACE_WITH_SMS_PROVIDER_KEY"
  sms_provider_secret: "REPLACE_WITH_SMS_PROVIDER_SECRET"
  email_provider_key: "REPLACE_WITH_EMAIL_PROVIDER_KEY"
  email_provider_secret: "REPLACE_WITH_EMAIL_PROVIDER_SECRET"
  
  # Monitoring credentials
  prometheus_basic_auth: "REPLACE_WITH_PROMETHEUS_BASIC_AUTH"
  
  # Additional security keys
  rate_limit_key: "REPLACE_WITH_RATE_LIMIT_KEY"
  session_key: "REPLACE_WITH_SESSION_KEY"
  csrf_key: "REPLACE_WITH_CSRF_KEY"

  # SSL certificates
  db_ssl_cert: |
    -----BEGIN CERTIFICATE-----
    Your SSL certificate here
    -----END CERTIFICATE-----
  db_ssl_key: |
    -----BEGIN PRIVATE KEY-----
    Your SSL key here
    -----END PRIVATE KEY-----

  # Redis SSL certificates
  redis_ssl_cert: |
    -----BEGIN CERTIFICATE-----
    Your Redis SSL certificate here
    -----END CERTIFICATE-----

  # External service URLs
  sms_api_url: "https://sms-provider.example.com"
  email_api_url: "https://email-provider.example.com"

  # Grafana basic authentication
  grafana_basic_auth: "admin:your-grafana-password" 