apiVersion: apps/v1
kind: Deployment
metadata:
  name: SERVICE_NAME
  namespace: sparkfund
  labels:
    app: SERVICE_NAME
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: SERVICE_NAME
  template:
    metadata:
      labels:
        app: SERVICE_NAME
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: SERVICE_NAME
        image: sparkfund/SERVICE_NAME:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: SERVICE_NAME-secrets
              key: db-host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: SERVICE_NAME-secrets
              key: db-port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: SERVICE_NAME-secrets
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: SERVICE_NAME-secrets
              key: db-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: SERVICE_NAME-secrets
              key: db-name
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: SERVICE_NAME-secrets
              key: jwt-secret
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: SERVICE_NAME-secrets
              key: encryption-key
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: SERVICE_NAME-secrets
              key: redis-host
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: SERVICE_NAME-secrets
              key: redis-port
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: SERVICE_NAME-secrets
              key: redis-password
        - name: LOG_LEVEL
          value: "info"
        - name: ENVIRONMENT
          value: "production"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: config
          mountPath: /app/config
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: config
        configMap:
          name: SERVICE_NAME-config
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME
  namespace: sparkfund
spec:
  selector:
    app: SERVICE_NAME
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: SERVICE_NAME-ingress
  namespace: sparkfund
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/rate-limit: "10r/s"
    nginx.ingress.kubernetes.io/rate-limit-burst: "20"
spec:
  tls:
  - hosts:
    - SERVICE_NAME.sparkfund.com
    secretName: SERVICE_NAME-tls
  rules:
  - host: SERVICE_NAME.sparkfund.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: SERVICE_NAME
            port:
              number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: SERVICE_NAME-config
  namespace: sparkfund
data:
  config.yaml: |
    server:
      port: 8080
      read_timeout: 30s
      write_timeout: 30s
      idle_timeout: 120s
    security:
      rate_limit:
        enabled: true
        requests_per_second: 10
        burst: 20
      cors:
        allowed_origins:
          - https://app.sparkfund.com
        allowed_methods:
          - GET
          - POST
          - PUT
          - DELETE
        allowed_headers:
          - Authorization
          - Content-Type
        max_age: 86400
    logging:
      level: info
      format: json
      output: stdout
    metrics:
      enabled: true
      path: /metrics
    audit:
      enabled: true
      retention_days: 90
      sensitive_fields:
        - password
        - credit_card
        - bank_account
