apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "money-pulse.fullname" . }}
  labels:
    {{- include "money-pulse.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "money-pulse.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "money-pulse.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "money-pulse.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_HOST
              value: {{ .Values.database.host | quote }}
            - name: DB_PORT
              value: {{ .Values.database.port | quote }}
            - name: DB_NAME
              value: {{ .Values.database.name | quote }}
            - name: DB_USER
              value: {{ .Values.database.user | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "money-pulse.fullname" . }}-db-credentials
                  key: password
            - name: ENVIRONMENT
              value: {{ .Values.environment | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.logLevel | quote }}
            # Account related environment variables
            - name: ACCOUNTS_ENABLED
              value: {{ .Values.accounts.enabled | quote }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /ready
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
