apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sparkfund
  namespace: argocd
spec:
  description: SparkFund Platform
  
  # Project sources
  sourceRepos:
    - 'https://github.com/adil-faiyaz98/sparkfund.git'
    - 'https://charts.jetstack.io'
    - 'https://kubernetes.github.io/ingress-nginx'
    - 'https://prometheus-community.github.io/helm-charts'
  
  # Destination clusters and namespaces
  destinations:
    - namespace: sparkfund
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: cert-manager
      server: https://kubernetes.default.svc
    - namespace: ingress-nginx
      server: https://kubernetes.default.svc
  
  # Cluster resource whitelist
  clusterResourceWhitelist:
    - group: '*'
      kind: Namespace
    - group: 'cert-manager.io'
      kind: '*'
  
  # Namespace resource whitelist
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  
  # Orphaned resources monitoring
  orphanedResources:
    warn: true
  
  # Sync windows
  syncWindows:
    # Allow syncing anytime for dev
    - applications:
        - '*-dev'
      clusters:
        - '*'
      namespaces:
        - '*'
      timeZone: America/New_York
      kind: allow
      schedule: '* * * * *'
      duration: 24h
    
    # Restrict syncing to non-business hours for prod
    - applications:
        - '*-prod'
      clusters:
        - '*'
      namespaces:
        - '*'
      timeZone: America/New_York
      kind: allow
      schedule: '0 0 * * *'  # Midnight every day
      duration: 6h
  
  # RBAC roles
  roles:
    - name: developer
      description: Developer role
      policies:
        - p, proj:sparkfund:developer, applications, get, sparkfund/*, allow
        - p, proj:sparkfund:developer, applications, sync, sparkfund/*, allow
      groups:
        - developers
    
    - name: admin
      description: Admin role
      policies:
        - p, proj:sparkfund:admin, applications, *, sparkfund/*, allow
      groups:
        - admins
