basePath: /api/v1
definitions:
  models.Attachment:
    properties:
      content:
        description: Base64 encoded content
        type: string
      content_type:
        type: string
      filename:
        type: string
    required:
    - content
    - content_type
    - filename
    type: object
  models.CreateTemplateRequest:
    properties:
      body:
        type: string
      description:
        type: string
      name:
        type: string
      subject:
        type: string
      variables:
        items:
          type: string
        type: array
    required:
    - body
    - name
    - subject
    - variables
    type: object
  models.EmailLog:
    properties:
      bcc:
        items:
          type: string
        type: array
      body:
        type: string
      cc:
        items:
          type: string
        type: array
      created_at:
        type: string
      error:
        type: string
      id:
        type: string
      status:
        type: string
      subject:
        type: string
      to:
        items:
          type: string
        type: array
      updated_at:
        type: string
    type: object
  models.EmailResponse:
    properties:
      message:
        type: string
    type: object
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.SendEmailRequest:
    properties:
      attachments:
        items:
          $ref: '#/definitions/models.Attachment'
        type: array
      bcc:
        items:
          type: string
        type: array
      body:
        type: string
      cc:
        items:
          type: string
        type: array
      data:
        additionalProperties:
          type: string
        type: object
      subject:
        type: string
      template_id:
        type: string
      to:
        items:
          type: string
        type: array
    required:
    - body
    - subject
    - to
    type: object
  models.Template:
    properties:
      body:
        type: string
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      subject:
        type: string
      updated_at:
        type: string
      variables:
        items:
          type: string
        type: array
    type: object
  models.UpdateTemplateRequest:
    properties:
      body:
        type: string
      description:
        type: string
      name:
        type: string
      subject:
        type: string
      variables:
        items:
          type: string
        type: array
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: A microservice responsible for sending emails and managing email templates.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Email Service API
  version: "1.0"
paths:
  /emails:
    get:
      consumes:
      - application/json
      description: Retrieve all email logs with optional filtering
      parameters:
      - description: Filter by status
        in: query
        name: status
        type: string
      - description: Filter by start date
        in: query
        name: from
        type: string
      - description: Filter by end date
        in: query
        name: to
        type: string
      - description: Limit number of results
        in: query
        name: limit
        type: integer
      - description: Offset for pagination
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.EmailLog'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get email logs
      tags:
      - emails
    post:
      consumes:
      - application/json
      description: Send an email to one or more recipients
      parameters:
      - description: Email request
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/models.SendEmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.EmailResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Send an email
      tags:
      - emails
  /logs:
    get:
      consumes:
      - application/json
      description: Get all email logs
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.EmailLog'
            type: array
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get email logs
      tags:
      - logs
  /send:
    post:
      consumes:
      - application/json
      description: Send an email with optional attachments
      parameters:
      - description: Email request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.SendEmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
        "503":
          description: Service Unavailable
          schema:
            additionalProperties: true
            type: object
      summary: Send an email
      tags:
      - email
  /template:
    post:
      consumes:
      - application/json
      description: Create a new email template
      parameters:
      - description: Template request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CreateTemplateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Template'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Create an email template
      tags:
      - template
  /template/{id}:
    delete:
      consumes:
      - application/json
      description: Delete an email template by ID
      parameters:
      - description: Template ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Delete an email template
      tags:
      - template
    get:
      consumes:
      - application/json
      description: Get an email template by ID
      parameters:
      - description: Template ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Template'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get an email template
      tags:
      - template
    put:
      consumes:
      - application/json
      description: Update an existing email template
      parameters:
      - description: Template ID
        in: path
        name: id
        required: true
        type: string
      - description: Template update request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.UpdateTemplateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Template'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Update an email template
      tags:
      - template
  /templates:
    post:
      consumes:
      - application/json
      description: Create a new email template
      parameters:
      - description: Template request
        in: body
        name: template
        required: true
        schema:
          $ref: '#/definitions/models.CreateTemplateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Template'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create a new template
      tags:
      - templates
  /templates/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a template by ID
      parameters:
      - description: Template ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Delete a template
      tags:
      - templates
    get:
      consumes:
      - application/json
      description: Retrieve a template by ID
      parameters:
      - description: Template ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Template'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get a template
      tags:
      - templates
    put:
      consumes:
      - application/json
      description: Update an existing template
      parameters:
      - description: Template ID
        in: path
        name: id
        required: true
        type: string
      - description: Template request
        in: body
        name: template
        required: true
        schema:
          $ref: '#/definitions/models.UpdateTemplateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Template'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Update a template
      tags:
      - templates
swagger: "2.0"
