server:
  port: "8080"
  read_timeout: 10
  write_timeout: 10
  max_header_bytes: 1048576  # 1MB
  max_request_size: 10485760  # 10MB
  allowed_origins:
    - "*"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Origin"
    - "Content-Type"
    - "Accept"
    - "Authorization"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "kyc"
  sslmode: "disable"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

logging:
  level: "info"
  format: "json"
  output: "stdout"
  max_size: 100
  max_backups: 3
  max_age: 28
  compress: true

security:
  jwt_secret: "your-secret-key"  # Change this in production
  jwt_expiry: 24
  rate_limit: 100
  rate_window: 60
  block_duration: 300 