app:
  name: "kyc-service"
  version: "1.0.0"
  environment: "development"

server:
  host: "0.0.0.0"
  port: 8081
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 120s
  shutdown_timeout: 30s
  timeout: 30s
  trusted_proxies:
    - 127.0.0.1
    - 172.16.0.0/12
    - 172.17.0.0/16
    - 192.168.0.0/16

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: kyc_service
  sslmode: disable
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 1h
  conn_max_idle_time: 10m

jwt:
  secret: "your-secret-key"
  expiry: 24h
  refresh: 168h
  issuer: sparkfund
  enabled: true

rate_limit:
  enabled: true
  requests: 60
  window: 1m
  burst: 10

metrics:
  enabled: true
  path: /metrics
  port: 9090
  push_interval: 10s

log:
  level: info
  format: json
  output: stdout
  request_log: true

circuit_breaker:
  enabled: true
  timeout: 30s
  max_concurrent_requests: 100
  error_threshold_percentage: 50
  request_volume_threshold: 20
  sleep_window: 5s

security:
  allowed_origins:
    - "*"
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed_headers:
    - Content-Type
    - Content-Length
    - Accept-Encoding
    - Authorization
    - X-CSRF-Token
  trusted_proxies:
    - 127.0.0.1
    - 172.16.0.0/12
    - 192.168.0.0/16
  enable_csrf: true
  jwt_secret: "your-secret-key"
  jwt_expiry: 24h
  rate_limit: 100
  rate_window: 60
  audit_logging:
    enabled: true
    log_predictions: true
    log_retention: "90d"
  access_control:
    role_based: true
    required_roles: ["ml-admin", "ml-operator"]

feature:
  enable_swagger: true
  enable_auth: true
  enable_metrics: true

feature_flags:
  ml_verification: true
  advanced_fraud_detection: true
  biometric_verification: false
  document_encryption: true
  audit_logging: true

tracing:
  enabled: true
  service_name: kyc-service
  sampling_rate: 0.1

cache:
  enabled: true
  type: memory  # memory or redis
  ttl: 5m
  cleanup_interval: 10m
  redis:
    host: localhost
    port: 6379
    password: ""
    db: 0
    prefix: kyc:

tls:
  enabled: false
  cert_file: ./certs/server.crt
  key_file: ./certs/server.key
  min_version: "1.2"

ai:
  service_url: http://localhost:8001
  api_key: your-api-key
  timeout: 30s
  max_retries: 3
  retry_delay: 1s
  models:
    document_verification:
      path: "gs://sparkfund-ml-models/kyc/doc-verify/v1"
      version: "2.0"
      batch_size: 32
      preprocessing:
        image_size: [224, 224]
        normalize: true
      security:
        encryption_enabled: true
        key_rotation_period: "30d"

    fraud_detection:
      path: "gs://sparkfund-ml-models/kyc/fraud-detect/v1"
      version: "2.0"
      threshold: 0.95
      real_time: true
      audit_logging: true

storage:
  type: "local"
  local:
    path: "/data/documents"
    temp_dir: "/tmp"
  s3:
    bucket: "kyc-documents"
    region: "us-east-1"
  retention:
    documents: "90d"
    verification_results: "180d"

validation:
  document:
    max_size: 10485760  # 10MB
    allowed_types:
      - "image/jpeg"
      - "image/png"
      - "application/pdf"
    min_resolution: 300
    max_pages: 10
  face:
    min_size: 150
    max_size: 1024
    allowed_formats:
      - "jpg"
      - "png"

notifications:
  enabled: true
  providers:
    email:
      smtp_host: "smtp.sparkfund.com"
      smtp_port: 587
      from_address: "kyc@sparkfund.com"
    sms:
      provider: "twilio"
      from_number: ""

monitoring:
  tracing:
    enabled: true
    sampling_rate: 0.1
  metrics:
    enabled: true
    push_interval: 10s
  alerts:
    enabled: true
    channels: ["slack", "pagerduty"]

events:
  enabled: true
  broker_type: "kafka"
  broker_url: "localhost:9092"
  topic_prefix: "kyc-"
