apiVersion: v1
kind: ConfigMap
metadata:
  name: accounts-config
  namespace: money-pulse
data:
  LOG_LEVEL: "info"
  ENVIRONMENT: "production"
  HTTP_PORT: "8080"
  GRPC_PORT: "50051"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-service
  namespace: money-pulse
  labels:
    app: accounts-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: accounts-service
  template:
    metadata:
      labels:
        app: accounts-service
    spec:
      containers:
      - name: accounts-service
        image: ghcr.io/adil-faiyaz98/money-pulse/accounts-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 50051
          name: grpc
        env:
        - name: DATABASE_URL
          value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)?sslmode=disable"
        envFrom:
        - configMapRef:
            name: accounts-config
        - secretRef:
            name: postgres-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-service
  namespace: money-pulse
  labels:
    app: accounts-service
spec:
  selector:
    app: accounts-service
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: grpc
    port: 50051
    targetPort: grpc
  type: ClusterIP