apiVersion: v1
kind: ConfigMap
metadata:
  name: transactions-config
  namespace: money-pulse
data:
  LOG_LEVEL: "info"
  ENVIRONMENT: "production"
  HTTP_PORT: "8080"
  GRPC_PORT: "50053"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-service
  namespace: money-pulse
  labels:
    app: transactions-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transactions-service
  template:
    metadata:
      labels:
        app: transactions-service
    spec:
      containers:
      - name: transactions-service
        image: ghcr.io/adil-faiyaz98/money-pulse/transactions-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 50053
          name: grpc
        env:
        - name: DATABASE_URL
          value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)?sslmode=disable"
        - name: ACCOUNTS_SERVICE_URL
          value: "accounts-service:50051"
        envFrom:
        - configMapRef:
            name: transactions-config
        - secretRef:
            name: postgres-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: transactions-service
  namespace: money-pulse
  labels:
    app: transactions-service
spec:
  selector:
    app: transactions-service
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: grpc
    port: 50053
    targetPort: grpc
  type: ClusterIP