apiVersion: v1
kind: ConfigMap
metadata:
  name: users-config
  namespace: money-pulse
data:
  LOG_LEVEL: "info"
  ENVIRONMENT: "production"
  HTTP_PORT: "8080"
  GRPC_PORT: "50052"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
  namespace: sparkfund
  labels:
    app: users-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
      - name: users-service
        image: ghcr.io/adil-faiyaz98/sparkfund/users-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: database
        envFrom:
        - configMapRef:
            name: users-config
        - secretRef:
            name: postgres-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: sparkfund
  labels:
    app: users-service
spec:
  selector:
    app: users-service
  ports:
  - name: http
    port: 8080
    targetPort: http
  type: ClusterIP