version: "3.8"

services:
  ai-service:
    build:
      context: .
    container_name: ai-service
    environment:
      DEBUG: "False"
      HOST: "0.0.0.0"
      PORT: "8000"
      API_KEY: "your-api-key"
      MODEL_PATH: "/app/models"
      UPLOAD_DIR: "/app/uploads"
    ports:
      - "8001:8000"
    volumes:
      - ai_uploads:/app/uploads
      - ai_models:/app/models
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  ai_uploads:
  ai_models:
