apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sparkfund-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: sparkfund
  
  source:
    repoURL: https://github.com/adil-faiyaz98/sparkfund.git
    targetRevision: HEAD
    path: deploy/helm/sparkfund
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
      values: |
        global:
          environment: staging
  
  destination:
    server: https://kubernetes.default.svc
    namespace: sparkfund-staging
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  # Health checks
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      jsonPointers:
        - /spec/metrics
