apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: money-pulse
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=           # postgres
  POSTGRES_PASSWORD: cG9zdGdyZXNwYXNzd29yZA==  # postgrespassword
  POSTGRES_DB: bW9uZXlfcHVsc2U=         # money_pulse