apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: sparkfund
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres
  password: c3BhcmtmdW5k  # sparkfund
  database: c3BhcmtmdW5k  # sparkfund