apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: money-pulse

bases:
- ../../base

resources:
- ../../infrastructure
- ../../services
- ../../scaling

configMapGenerator:
- name: accounts-config
  behavior: merge
  literals:
  - LOG_LEVEL=debug
  - ENVIRONMENT=development

- name: users-config
  behavior: merge
  literals:
  - LOG_LEVEL=debug
  - ENVIRONMENT=development

- name: transactions-config
  behavior: merge
  literals:
  - LOG_LEVEL=debug
  - ENVIRONMENT=development

patches:
- target:
    kind: Deployment
    name: accounts-service
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
- target:
    kind: Deployment
    name: users-service
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
- target:
    kind: Deployment
    name: transactions-service
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1