allInOne:
  enabled: true
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch:9200
        username: elastic
        password: changeme

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - jaeger.sparkfund.com
    tls:
      - secretName: jaeger-tls
        hosts:
          - jaeger.sparkfund.com

  service:
    type: ClusterIP
    ports:
      - name: http-query
        port: 16686
        targetPort: 16686
      - name: http-collector
        port: 14268
        targetPort: 14268
      - name: grpc-collector
        port: 14250
        targetPort: 14250

  options:
    log-level: info
    service:
      metrics:
        storage:
          type: prometheus
          options:
            prometheus:
              server-url: http://prometheus-server:9090
    storage:
      type: elasticsearch
      options:
        es:
          server-urls: http://elasticsearch:9200
          username: elastic
          password: changeme
    dependencies:
      enabled: true
    collector:
      zipkin:
        host-port: :9411
    query:
      base-path: /jaeger
      static-files: /usr/share/jaeger/html
    agent:
      options:
        log-level: info 