openapi: 3.0.0
info:
  title: Money Pulse API
  version: 1.0.0
  description: API documentation for Money Pulse microservices
servers:
  - url: http://localhost:8080
    description: Local development server
  - url: https://api.moneypulse.com
    description: Production server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
    Account:
      type: object
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        type:
          type: string
          enum: [SAVINGS, CHECKING, INVESTMENT, CREDIT]
        name:
          type: string
        accountNumber:
          type: string
        balance:
          type: number
          format: float64
        currency:
          type: string
          default: USD
        status:
          type: string
          enum: [ACTIVE, INACTIVE, FROZEN]
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        firstName:
          type: string
        lastName:
          type: string
        status:
          type: string
          enum: [ACTIVE, INACTIVE, SUSPENDED]
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Transaction:
      type: object
      properties:
        id:
          type: string
          format: uuid
        accountId:
          type: string
          format: uuid
        type:
          type: string
          enum: [DEPOSIT, WITHDRAWAL, TRANSFER, PAYMENT]
        amount:
          type: number
          format: float64
        currency:
          type: string
          default: USD
        status:
          type: string
          enum: [PENDING, COMPLETED, FAILED, CANCELLED]
        description:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Loan:
      type: object
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        type:
          type: string
          enum: [PERSONAL, BUSINESS, MORTGAGE, AUTO]
        amount:
          type: number
          format: float64
        interestRate:
          type: number
          format: float64
        term:
          type: integer
          description: Loan term in months
        status:
          type: string
          enum: [PENDING, APPROVED, REJECTED, PAID]
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Investment:
      type: object
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        type:
          type: string
          enum: [STOCKS, BONDS, MUTUAL_FUNDS, CRYPTO]
        amount:
          type: number
          format: float64
        status:
          type: string
          enum: [ACTIVE, SOLD, PENDING]
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Report:
      type: object
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        type:
          type: string
          enum: [BALANCE_SHEET, INCOME_STATEMENT, CASH_FLOW]
        period:
          type: string
          enum: [DAILY, WEEKLY, MONTHLY, YEARLY]
        data:
          type: object
        createdAt:
          type: string
          format: date-time 