name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_USERNAME: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download

      - name: Test
        run: go test -v ./...

  build-and-push:
    name: Build and Push
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [accounts-service, users-service, transactions-service]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./services/${{ matrix.service }}
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ github.repository_owner }}/money-pulse/${{ matrix.service }}:latest,${{ env.DOCKER_REGISTRY }}/${{ github.repository_owner }}/money-pulse/${{ matrix.service }}:${{ github.sha }}

  deploy:
    name: Deploy to EKS
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name money-pulse-cluster --region us-west-2

      - name: Deploy to EKS
        run: |
          # Update image tags in deployment files
          for service in accounts-service users-service transactions-service; do
            sed -i "s|\${DOCKER_REGISTRY}/money-pulse/$service:latest|${{ env.DOCKER_REGISTRY }}/${{ github.repository_owner }}/money-pulse/$service:${{ github.sha }}|g" k8s/$service.yaml
          done

          # Apply Kubernetes manifests
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/postgres.yaml
          kubectl apply -f k8s/accounts-service.yaml
          kubectl apply -f k8s/users-service.yaml
          kubectl apply -f k8s/transactions-service.yaml
          kubectl apply -f k8s/ingress.yaml
          kubectl apply -f k8s/hpa.yaml
