name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Or your main branch name
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Get dependencies
        run: go mod tidy
        working-directory: ./investment-service

      - name: Run tests
        run: go test -v ./...
        working-directory: ./investment-service

      - name: Build Docker image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/investment-service:latest ./investment-service
        env:
          DOCKER_BUILDKIT: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only deploy on pushes to main
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: "latest"
          credentials: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker authentication
        run: |-
          gcloud auth configure-docker gcr.io

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy investment-service \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/investment-service:latest \
            --region us-central1 \ # Replace with your region
            --platform managed \
            --allow-unauthenticated \ # Remove this for production with authentication
            --update-env-vars PORT=8080,DB_HOST=...,DB_PORT=...,DB_USER=...,DB_NAME=... \ # Add other env vars
            --update-secrets DB_PASSWORD=...,SMTP_USERNAME=...,SMTP_PASSWORD=... # Add secrets
