app:
  environment: "production"

server:
  port: 8080

database:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "${DB_PASSWORD}"
  name: "service_template"
  sslmode: "require"

log:
  level: "info"
  format: "json"

jwt:
  secret: "${JWT_SECRET}"

cache:
  enabled: true
  type: "redis"
  redis:
    host: "redis"
    port: 6379
    password: "${REDIS_PASSWORD}"
