# Default values for PostgreSQL
image:
  repository: postgres
  tag: "15-alpine"
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  size: 1Gi
  storageClass: ""

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}