version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    container_name: investment-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: investment_service
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  investment-service:
    build:
      context: .
      target: production
    container_name: investment-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      APP_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: investment_service
      DB_SSL_MODE: disable
      JWT_SECRET: your-jwt-secret
      AWS_REGION: us-east-1
    ports:
      - "8082:8080"
    volumes:
      - ./uploads:/data/investments
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  postgres_data:
